### ISSUE TITLE
CRLF (and maybe LFCR) should be treated as a single linebreak

### ISSUE THREAD

**Issue by zypA13510** [Jaid/prepend-to-lines#19]
https://runkit.com/embed/f5nyw5qee3b0
Note that `\r\n` is treated as two linebreaks.
As for LFCR, well, it's rare but [not unheard of](https://en.wikipedia.org/wiki/Newline#Representation).

**Comment by Jaid** [comment]
`prependToLines` relies on the RegEx token `.` to decide which characters belong to the same line. I would like not to switch from that standardized way of determining line breaks to a custom way of determining line breaks to keep the results predictable in edge cases. Sorry for that!

But the first argument can be also a pre-split array of strings, to this is possible:

Code
```js
const text = "a\r\nb\nc"
const lines = text.split(/[\n\r]+/) // This splits the string on any single or multi occurence of \n and \r in any order
const result = prependToLines(lines, "* ")
```

Result
```
* a
* b
* c
```

**Comment by zypA13510** [comment]
Yes, I have read your source before creating this issue.

I think the primary issue here is not whether `/./` is standard, it's usability (if a simple and standard way exists, people have no reason to use an additional package just to do what 1 line of code can do). All I'm saying is, this tool is not cross-platform. It says prepend to lines, but it only detects UNIX lines. And the second way you provided just throw the issue back to users (again, why not use `string.replace(/^/gm, 'to-be-prepended')` if that's the case)

But I'm not the owner so, feel free to keep it your way.
